language: cpp
env:
  global: 
    - secure: "gngXreGlUA1bOulP+Qjj7C2SbOC8oh5tewD039f/VHNbw01EsQA4cLYTgpIOxr+AhlDgBmn6h/o3b+Rql9Jv/trtBxYmrlpNxoZP9XdrcjfFeMThehbwABrqA5U8WU51Fuvnw4ogHzItV9xea5yetSSwO7S30P0eoYdfUwIa/gtCB9No+Ry+qZntupmw9Dt+Gy+Cb6JDT0feuegbxXmY3cjyX48+Je2TvZyJ+pKIuMDNNRwI4eW7kEDItP0grN8O8hGRKEYQnKjawEYKp5g+l6lSs1Ti4g68EtZPdtDzeW/aqfpLbAXUzUG/6hAe/kockioCuJI+Ut/ANoWfUoV0YxlfvqfOTfjU2xM648BWHeHO214f+0uXs18oxaDpv4JLKZHgL+F8+kMAEwRWmtpWp5oztZyAmFdJF8D9j9Tv/v47xZdvCNlkhrfO3UqS8SSAmzbVYK/x1mCxUdaWSdYLVLgVZRLOupTo2HzhiSzCJ+Epv5I/usPSeJtdN/w/NWfLhev4KoODd/74+u58YAoArQyRV/GMqXD6MnTqyieDdM6oVd6U2zS2yqr1Mim/NOBc82NejMO9zoodMGpankHSx/FKxbhiMc0ArAradIABmmXsd9BS018McMZj5iKq1VzZ4ahvwv4d2Pgliyd1CTCx+14YCtVvtZ6UW4Iq+aI7ejo="
    
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gfortran
    - os: osx
      osx_image: osx10.11
      env: OSX=10.11
      compiler: clang
    - os: osx
      osx_image: xcode7
      env: OSX=10.10
      compiler: clang
    - os: osx
      osx_image: beta-xcode6.2
      env: OSX=10.9
      compiler: clang
  allow_failures:
    - os: osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  export PLATFORM=osx$OSX-x86_64-clang`clang -dumpversion`; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$OSX" == "10.10" ]]; then brew update; brew install gcc; export PLATFORM=osx10.10-x86_64-clang`clang -dumpversion`; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PLATFORM=linux-x86_64-gcc`gcc -dumpversion`; fi
  - git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools
  - bash BuildTools/get.dependencies.sh fetch > /dev/null

script:
  - patch -p0 < SYMPHONY/Osi.patch
  - bash BuildTools/get.dependencies.sh build --quiet --test

after_script:
  - if [ $TRAVIS_BRANCH = "master" ]; then export VERSION=trunk; else export VERSION=`echo $TRAVIS_BRANCH | cut -d "/" -f 2`; fi
  - export PROJECT=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
  - export TGZ_FILE=`echo $PROJECT-$VERSION-$PLATFORM.tgz
  - tar -czvf $TGZ_FILE SYMPHONY/lib/* SYMPHONY/bin/* SYMPHONY/include/* SYMPHONY/share/*
  - curl -T $TGZ_FILE -utkralphs:$BINTRAY_API -H "X-Bintray-Publish:1" -H "X-Bintray-Override:1" https://api.bintray.com/content/coin-or/generic/$PROJECT/$VERSION/$TGZ_FILE